export { default as HomePage } from './HomePage/HomePage.jsx'
export { default as Exchanges } from './Exchanges/Exchanges'
export { default as Cryptocurrencies } from './Cryptocurrencies/Cryptocurrencies'
export { default as CryptoDetails } from './CryptoDetails/CryptoDetails'
export { default as News } from './News/News'